#!/bin/sh

function abort {
    echo $1
    echo "\nAborting..."
    exit 1
}

if [[ "$#" -ne 1 ]]; then 
    me=`basename "$0"`
    echo "Usage: ./${me} sourcefile"  
    exit
fi

sourcefile="${PWD}/$1"

# change cwd to the location of this script
cd "${0%/*}"

if [[ ! -e "../patched-roms" ]] ; then
    mkdir ../patched-roms
fi

if [[ ! -e $sourcefile ]] ; then
    abort "\"$1\" not found."
fi

sourcefile_basename=${sourcefile##*/}
original_rom_filename=$(sed -n 's/^; ROM "\(.*\)"/\1/p' "$sourcefile")
original_rom_path="../original-roms/${original_rom_filename}"

if [[ ! -e $original_rom_path ]] ; then
    abort "Orignal ROM not found in \"${original_rom_path}\"."
fi


# check if the md5 hash of the original rom is correct
echo "Verifying md5 hash of \"${original_rom_filename}\"..."
original_rom_md5=`md5 -q "${original_rom_path}"`
required_md5=`grep md5 "${sourcefile}" | cut -d " " -f 3`

if [[ $original_rom_md5 != $required_md5 ]]; then
    abort "ROM in original-roms directory has md5 hash ${original_rom_md5}. Require ${required_md5}. Aborting..."
fi

# create checksum file
original_rom_checksum_path="../checksums/${original_rom_filename}.md5"
echo $original_rom_md5 > "${original_rom_checksum_path}"

cp "${original_rom_path}" "${original_rom_filename}"


echo "Assembling patched ROM..."
rgbasm -o "patched.o" "${sourcefile}"

if [ $? -ne 0 ]; then
    rm "${original_rom_filename}"
    abort "Error occurred assembling patched ROM."
fi


echo "Linking patched ROM..."
rgblink -p0 -o "patched.gb" -O "${original_rom_path}" "patched.o"

if [ $? -ne 0 ]; then
    rm patched.o
    rm "${original_rom_filename}"
    abort "Error occurred linking patched ROM."
fi

echo "Fixing patched ROM..."
rgbfix -p0 -v "patched.gb"

echo "Creating patch..."
bsdiff "${original_rom_path}" "patched.gb" "patch.bsdiff"

# move results into place
if grep "DEF is_cgb EQU 1" "${sourcefile}" >/dev/null; then
  cp patch.bsdiff "../patches/cgb/${original_rom_filename}.bsdiff"
else
  cp patch.bsdiff "../patches/${original_rom_filename}.bsdiff"
fi
mv patched.gb "../patched-roms/${original_rom_filename}"

# clean up
rm patch.bsdiff
rm patched.o
rm "${original_rom_filename}"

echo "Done!"
